name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: guju8cvl
          MYSQL_DATABASE: ris_todo
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..60}; do
            if mysqladmin ping -h127.0.0.1 --silent; then
              echo "MySQL is ready"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Verify MySQL Connectivity
        run: |
          mysql -uroot -pguju8cvl -h127.0.0.1 -e "USE ris_todo;"

      - name: Build backend
        run: |
          cd Todo/todo-backend
          mvn clean install -X

  build-frontend:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '>=20.0.0'

      - name: Install dependencies
        run: |
          cd Todo/todo-frontend
          npm install

      - name: Build frontend
        env:
          CI: false
        run: |
          cd Todo/todo-frontend
          npm run build

  test-backend:
    runs-on: ubuntu-latest
    needs: build-backend
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: "guju8cvl"
          MYSQL_DATABASE: ris_todo
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..60}; do
            if mysqladmin ping -hmysql --silent; then
              echo "MySQL is ready"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Check MySQL connectivity
        run: |
          mysql -uroot -pguju8cvl -hmysql -e 'SELECT 1'

      - name: Run backend tests
        env:
          DB_HOST: mysql
          DB_PORT: 3306
          DB_NAME: ris_todo
          DB_USER: root
          DB_PASSWORD: "guju8cvl"
        run: |
          cd Todo/todo-backend
          mvn test