name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE epski_rizz;' -uroot -proot    

      - name: Clear Maven cache
          run: rm -rf ~/.m2/repository

      - name: Build backend
        run: |
          cd Todo/todo-backend
          mvn clean install -X
        env:
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

  build-frontend:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '>=20.0.0'

      - name: Install dependencies and build frontend
        run: |
          cd Todo/todo-frontend
          npm install
          npm run build

  test-backend:
    runs-on: ubuntu-latest
    needs: build-backend
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_DATABASE: epski_rizz
          MYSQL_USER: root
          MYSQL_PASSWORD: ""
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..60}; do
            if mysqladmin ping -h mysql --silent; then
              echo "MySQL is ready"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Check MySQL connectivity
        run: |
          docker exec -it mysql mysql -uroot -e 'SELECT 1'

      - name: Run backend tests
        env:
          DB_HOST: mysql
          DB_PORT: 3306
          DB_NAME: epski_rizz
          DB_USER: root
          DB_PASSWORD: ""
        run: |
          cd Todo/todo-backend
          mvn test
